{{- if .Values.ingress.acme }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "mesh.fullname" . }}-config
  labels:
    app: {{ template "mesh.name" . }}
    chart: {{ template "mesh.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  acme:
    config:
    - dns01:
        provider: gcp-dns
      domains:
      - '*.{{ .Release.Name }}.{{ .Values.global.domain }}'
  dnsNames:
  - '*.{{ .Release.Name }}.{{ .Values.global.domain }}'
  issuerRef:
    kind: ClusterIssuer
    name: certmanager-letsencrypt-prod
  secretName: {{ template "certificate.fullname" . }}
{{- end }}