{{- if and (eq .Values.persistence.nfs.enabled true) (eq .Values.persistence.enabled true) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mesh.fullname" . }}-restore
  labels:
    app.kubernetes.io/name: {{ include "mesh.name" . }}
    helm.sh/chart: {{ include "mesh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mesh.name" . }}-restore
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mesh.name" . }}-restore
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: restore-job
          image: "gentics/mesh-tools:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          {{/*command: ["/bin/sh", "/config/backup.sh"]*/}}
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo 'invoke manually /config/restore.sh inside this pod to restore mesh to latest available backup'; sleep 30;done"]
          env:
          - name: "MESH_HOST"
            value: {{ template "mesh.fullname" . }}-master.{{ .Release.Namespace }}.svc.cluster.local:8080
          - name: "ORIENTDB_BACKUP_RESTORE_DIRECTORY"
            value: "/backups-nfs/orientdb"
          - name: "BACKUP_HISTORY_FOLDER"
            value: "/backups-nfs/history"
          - name: "BACKUP_TMP_FOLDER"
            value: "/backups-nfs/tmp"
          - name: MESH_CLUSTER_NAME
            value: cluster-{{ template "mesh.version.slug" . }}
          - name: MESH_CLUSTER_ENABLED # replica cannot work without cluster
            value: "true"
          - name: "hazelcast.kubernetes.service-dns"
            value: {{ template "mesh.fullname" . }}-hazelcast.{{ .Release.Namespace }}.svc.cluster.local
          - name: MESH_ELASTICSEARCH_URL
            value: {{ tpl .Values.elasticsearch.url . | quote }}
        {{- range $name, $value := .Values.mesh.additionalEnvironmentVariables }}
          - name: {{ tpl $name $ }}
            value: {{ tpl $value $ }}
        {{- end }}
          volumeMounts:
          - name: mesh-config
            mountPath: "/config"
          - name: mesh-uploads
            mountPath: "/uploads"
            subPath: {{ template "mesh.fullname.no.override" . }}-uploads
          - name: mesh-uploads
            mountPath: "/backups-nfs"
            subPath: {{ template "mesh.fullname.no.override" . }}-backups
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 50m
              memory: 128Mi
      volumes:
      - name: mesh-config
        configMap:
          name: {{ template "mesh.fullname" . }}-config
      - name: mesh-uploads
        persistentVolumeClaim:
          claimName: {{ template "mesh.fullname.no.override" . }}-uploads
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
