{{- if and (eq .Values.persistence.nfs.enabled true) (eq .Values.persistence.enabled true) }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "mesh.fullname" . }}-backup-explorer
  labels:
    app.kubernetes.io/name: {{ include "mesh.name" . }}
    helm.sh/chart: {{ include "mesh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mesh.name" . }}-backup-explorer
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mesh.name" . }}-backup-explorer
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: backup-explorer
          image: "httpd:alpine"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
          - name: htdocs-root
            mountPath: "/usr/local/apache2/htdocs"
          - name: mesh-uploads
            mountPath: "/usr/local/apache2/htdocs/nfs-fileserver"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 32Mi
      volumes:
      - name: htdocs-root
        emptyDir: {}
      - name: mesh-uploads
        persistentVolumeClaim:
          claimName: {{ template "mesh.fullname.no.override" . }}-uploads
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
